# Generated by Django 2.1.7 on 2019-04-01 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZxgkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', '失信'), ('B', '仅被执行人'), ('Z', '终本结案信息'), ('X', '限制高消费')], max_length=1)),
                ('areaName', models.CharField(max_length=32)),
                ('cardNum', models.CharField(max_length=20)),
                ('caseCode', models.CharField(max_length=64)),
                ('courtName', models.CharField(max_length=32)),
                ('disruptTypeName', models.CharField(max_length=64)),
                ('duty', models.TextField()),
                ('gistId', models.CharField(max_length=32)),
                ('gistUnit', models.CharField(max_length=32)),
                ('iname', models.CharField(max_length=8)),
                ('performance', models.CharField(max_length=32)),
                ('publishDate', models.CharField(max_length=32)),
                ('regDate', models.CharField(max_length=32)),
                ('sexy', models.CharField(max_length=8)),
                ('execMoney', models.CharField(max_length=16)),
                ('finalDate', models.CharField(max_length=32)),
                ('unperformMoney', models.CharField(max_length=16)),
                ('spiderTime', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zxgkinfo',
            unique_together={('type', 'caseCode', 'cardNum')},
        ),
    ]
